-- This file is automatically generated by the update.sh script.
-- Do not edit this file directly, as it will be overwritten.
-- If you want to make changes, use the Overrides.lua file instead.

local _, ns = ...

local Spells = {}
local SpellsNoTank = {}
local Auras = {}
local AurasNoTank = {}
local MeleeHitters = {}


ns.ehdb = {}
ns.ehdb.Spells = Spells
ns.ehdb.SpellsNoTank = SpellsNoTank
ns.ehdb.Auras = Auras
ns.ehdb.AurasNoTank = AurasNoTank
ns.ehdb.MeleeHitters = MeleeHitters
